apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2
  name: amr-api-ingress-be
spec:
  ingressClassName: nginx
  rules:
  - host: www.ebi.ac.uk
    http:
      paths:
      - backend:
          service:
            name: amr-api-svc
            port:
              number: 8000
        path: /amr/api(/|$)(.*)
        pathType: Prefix
