apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: amr-api-ingress-fe
spec:
  ingressClassName: nginx
  rules:
  - host: amr.review.ensembl.org
    http:
      paths:
      - backend:
          service:
            name: amr-frontend-svc
            port:
              number: 8000
        path: /amr(/|$)(.*)
        pathType: Prefix