apiVersion: v1
kind: Service
metadata:
  name: amr-api-svc
  labels:
    ensembl.platform.app.name: amr
spec:
  selector:
    ensembl.platform.app.name: amr
  type: ClusterIP
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
